name: CI Pipeline - Test, Build & Push

on:
 push:
   branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Java JDK
        uses: actions/setup-java@v3 
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give Gradle permissions
        run: chmod +x gradlew

      - name: Run Gradle tests
        run: ./gradlew test
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-petclinic:latest

        


        
        

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        
